apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-chart
  namespace: my-chart-ns
  labels:
    app: my-chart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-chart
  template:
    metadata:
      labels:
        app: my-chart
    spec:
      containers:
      - name: my-chart
        image: davescreen/gitops-foundations:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
