apiVersion: v1
kind: Service
metadata:
  name: my-chart
  annotations:
  namespace: my-chart-ns
spec:
  type: LoadBalancer
  selector:
    app: my-chart
  ports:
    - port: 80
      targetPort: 8080
